version: "3"

services:
  henkan:
    build: ./henkan
    ports:
      - "5000:5000"
    volumes:
      - "./henkan:/henkan"
    working_dir: /henkan
    command: python3 serv.py
  update:
    build: ./update
    ports:
      - "5001:5001"
    volumes:
      - "./update:/update"
    working_dir: /update
    command: python3 serv.py
